/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary': '#213337',
        'on-error-container': '#ffdad6',
        'on-surface-variant': '#c2c7c9',
        'primary-fixed': '#d2e6eb',
        'surface-container-lowest': '#0d0e0f',
        'on-tertiary-fixed-variant': '#394856',
        'error': '#ffb4ab',
        'on-tertiary': '#23323f',
        'on-tertiary-container': '#556473',
        'surface-container-highest': '#343535',
        'on-tertiary-fixed': '#0d1d29',
        'background': '#131314',
        'tertiary-fixed-dim': '#b8c8d9',
        'inverse-surface': '#e4e2e2',
        'inverse-primary': '#4f6166',
        'primary-fixed-dim': '#b6cacf',
        'surface': '#131314',
        'outline': '#8c9293',
        'error-container': '#93000a',
        'secondary-fixed-dim': '#cdc1e1',
        'surface-dim': '#131314',
        'on-secondary-fixed': '#1e182f',
        'outline-variant': '#424849',
        'surface-container-high': '#292a2a',
        'surface-container': '#1f2020',
        'secondary-fixed': '#e9ddfe',
        'on-secondary-container': '#beb3d3',
        'on-primary-fixed-variant': '#384a4e',
        'on-secondary': '#342c45',
        'surface-tint': '#b6cacf',
        'on-primary-container': '#53666a',
        'inverse-on-surface': '#303031',
        'tertiary': '#fbfcff',
        'primary': '#f7fdff',
        'tertiary-container': '#d1e1f3',
        'on-surface': '#e4e2e2',
        'surface-variant': '#343535',
        'on-error': '#690005',
        'secondary-container': '#4d455f',
        'primary-container': '#cfe3e8',
        'on-primary-fixed': '#0b1e22',
        'on-secondary-fixed-variant': '#4a435d',
        'secondary': '#cdc1e1',
        'surface-bright': '#393939',
        'tertiary-fixed': '#d4e4f6',
        'on-background': '#e4e2e2',
        'surface-container-low': '#1b1c1c',
      },
      borderRadius: {
        'custom': '0.5rem',
      },
      spacing: {
        'container-max': '1280px',
        'margin-desktop': '64px',
        'margin-mobile': '16px',
        'unit': '8px',
        'gutter': '24px',
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
